# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          "C.J"
paginate:       5
baseurl:        ""
url:            "https://bexonp.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Bexon
  url:          https://bexonp.github.io
  email:        chaojie149@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/bexonp

# Gems
gems:
  - jekyll-paginate
theme: jekyll-theme-modernist